import { HazmatPlacard } from '@/types';

export const hazmatPlacards: HazmatPlacard[] = [
  // Class 1 - Explosives
  {
    id: 'class1_1',
    name: 'Explosives 1.1',
    class: '1',
    division: '1.1',
    color: 'Orange',
    symbol: 'Exploding bomb',
    description: 'Mass explosion hazard',
    compatibilityGroup: 'A-S',
    segregationTable: 'Table 1',
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?q=80&w=400',
  },
  {
    id: 'class1_2',
    name: 'Explosives 1.2',
    class: '1',
    division: '1.2',
    color: 'Orange',
    symbol: 'Exploding bomb',
    description: 'Projection hazard',
    compatibilityGroup: 'A-S',
    segregationTable: 'Table 1',
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?q=80&w=400',
  },
  {
    id: 'class1_3',
    name: 'Explosives 1.3',
    class: '1',
    division: '1.3',
    color: 'Orange',
    symbol: 'Exploding bomb',
    description: 'Fire hazard',
    compatibilityGroup: 'A-S',
    segregationTable: 'Table 1',
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?q=80&w=400',
  },
  {
    id: 'class1_4',
    name: 'Explosives 1.4',
    class: '1',
    division: '1.4',
    color: 'Orange',
    symbol: 'Exploding bomb',
    description: 'Minor explosion hazard',
    compatibilityGroup: 'A-S',
    segregationTable: 'Table 2',
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?q=80&w=400',
  },
  {
    id: 'class1_5',
    name: 'Explosives 1.5',
    class: '1',
    division: '1.5',
    color: 'Orange',
    symbol: 'Exploding bomb',
    description: 'Very insensitive explosives',
    compatibilityGroup: 'D',
    segregationTable: 'Table 2',
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?q=80&w=400',
  },
  {
    id: 'class1_6',
    name: 'Explosives 1.6',
    class: '1',
    division: '1.6',
    color: 'Orange',
    symbol: 'Exploding bomb',
    description: 'Extremely insensitive explosives',
    compatibilityGroup: 'N',
    segregationTable: 'Table 2',
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?q=80&w=400',
  },

  // Class 2 - Gases
  {
    id: 'class2_1',
    name: 'Flammable Gas',
    class: '2',
    division: '2.1',
    color: 'Red',
    symbol: 'Flame',
    description: 'Flammable gas',
    segregationTable: 'Table 1',
    imageUrl: 'https://images.unsplash.com/photo-1574263867128-a3d5c1b1deaa?q=80&w=400',
  },
  {
    id: 'class2_2',
    name: 'Non-Flammable Gas',
    class: '2',
    division: '2.2',
    color: 'Green',
    symbol: 'Gas cylinder',
    description: 'Non-flammable, non-toxic gas',
    segregationTable: 'Table 2',
    imageUrl: 'https://images.unsplash.com/photo-1574263867128-a3d5c1b1deaa?q=80&w=400',
  },
  {
    id: 'class2_3',
    name: 'Toxic Gas',
    class: '2',
    division: '2.3',
    color: 'White',
    symbol: 'Skull and crossbones',
    description: 'Toxic gas',
    segregationTable: 'Table 1',
    imageUrl: 'https://images.unsplash.com/photo-1574263867128-a3d5c1b1deaa?q=80&w=400',
  },

  // Class 3 - Flammable Liquids
  {
    id: 'class3',
    name: 'Flammable Liquid',
    class: '3',
    color: 'Red',
    symbol: 'Flame',
    description: 'Flammable liquid',
    segregationTable: 'Table 1',
    imageUrl: 'https://images.unsplash.com/photo-1582719471384-894fbb16e074?q=80&w=400',
  },

  // Class 4 - Flammable Solids
  {
    id: 'class4_1',
    name: 'Flammable Solid',
    class: '4',
    division: '4.1',
    color: 'White with red stripes',
    symbol: 'Flame',
    description: 'Flammable solid',
    segregationTable: 'Table 2',
    imageUrl: 'https://images.unsplash.com/photo-1582719471384-894fbb16e074?q=80&w=400',
  },
  {
    id: 'class4_2',
    name: 'Spontaneously Combustible',
    class: '4',
    division: '4.2',
    color: 'Red and white',
    symbol: 'Flame',
    description: 'Spontaneously combustible material',
    segregationTable: 'Table 1',
    imageUrl: 'https://images.unsplash.com/photo-1582719471384-894fbb16e074?q=80&w=400',
  },
  {
    id: 'class4_3',
    name: 'Dangerous When Wet',
    class: '4',
    division: '4.3',
    color: 'Blue',
    symbol: 'Flame and W',
    description: 'Dangerous when wet',
    segregationTable: 'Table 1',
    imageUrl: 'https://images.unsplash.com/photo-1582719471384-894fbb16e074?q=80&w=400',
  },

  // Class 5 - Oxidizers
  {
    id: 'class5_1',
    name: 'Oxidizer',
    class: '5',
    division: '5.1',
    color: 'Yellow',
    symbol: 'Flame over circle',
    description: 'Oxidizer',
    segregationTable: 'Table 1',
    imageUrl: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?q=80&w=400',
  },
  {
    id: 'class5_2',
    name: 'Organic Peroxide',
    class: '5',
    division: '5.2',
    color: 'Red and yellow',
    symbol: 'Flame over circle',
    description: 'Organic peroxide',
    segregationTable: 'Table 1',
    imageUrl: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?q=80&w=400',
  },

  // Class 6 - Toxic Materials
  {
    id: 'class6_1',
    name: 'Toxic Material',
    class: '6',
    division: '6.1',
    color: 'White',
    symbol: 'Skull and crossbones',
    description: 'Toxic material',
    segregationTable: 'Table 1',
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?q=80&w=400',
  },
  {
    id: 'class6_2',
    name: 'Infectious Substance',
    class: '6',
    division: '6.2',
    color: 'White',
    symbol: 'Biohazard',
    description: 'Infectious substance',
    segregationTable: 'Table 1',
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?q=80&w=400',
  },

  // Class 7 - Radioactive
  {
    id: 'class7',
    name: 'Radioactive',
    class: '7',
    color: 'White and yellow',
    symbol: 'Trefoil',
    description: 'Radioactive material',
    segregationTable: 'Table 1',
    imageUrl: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?q=80&w=400',
  },

  // Class 8 - Corrosive
  {
    id: 'class8',
    name: 'Corrosive',
    class: '8',
    color: 'Black and white',
    symbol: 'Liquid dropping on hand and metal',
    description: 'Corrosive material',
    segregationTable: 'Table 2',
    imageUrl: 'https://images.unsplash.com/photo-1582719471384-894fbb16e074?q=80&w=400',
  },

  // Class 9 - Miscellaneous
  {
    id: 'class9',
    name: 'Miscellaneous',
    class: '9',
    color: 'Black and white stripes',
    symbol: 'Various',
    description: 'Miscellaneous hazardous material',
    segregationTable: 'Table 2',
    imageUrl: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?q=80&w=400',
  },
];

export const commonHazmatMaterials = [
  {
    unNumber: 'UN1203',
    properShippingName: 'Gasoline',
    hazardClass: '3',
    packingGroup: 'II',
    placards: ['class3'],
    emergencyContact: '1-800-424-9300',
    specialInstructions: [
      'Keep away from heat, sparks, and flames',
      'Use explosion-proof electrical equipment',
      'Ground and bond containers during transfer',
    ],
  },
  {
    unNumber: 'UN1005',
    properShippingName: 'Ammonia, anhydrous',
    hazardClass: '2.3',
    packingGroup: 'I',
    placards: ['class2_3'],
    emergencyContact: '1-800-424-9300',
    specialInstructions: [
      'Extremely dangerous - toxic gas',
      'Use full protective equipment',
      'Evacuate area if leak occurs',
    ],
  },
  {
    unNumber: 'UN1824',
    properShippingName: 'Sodium hydroxide solution',
    hazardClass: '8',
    packingGroup: 'II',
    placards: ['class8'],
    emergencyContact: '1-800-424-9300',
    specialInstructions: [
      'Corrosive to skin and eyes',
      'Use chemical-resistant gloves',
      'Have eyewash station available',
    ],
  },
  {
    unNumber: 'UN1072',
    properShippingName: 'Oxygen, compressed',
    hazardClass: '2.2',
    packingGroup: 'N/A',
    placards: ['class2_2'],
    emergencyContact: '1-800-424-9300',
    specialInstructions: [
      'Oxidizer - increases fire intensity',
      'Keep away from flammable materials',
      'Secure cylinders during transport',
    ],
  },
];

export const segregationTable = {
  'Table 1': {
    description: 'Load, transport, or store together only under specific conditions',
    restrictions: [
      'Separate by at least 5 feet',
      'Use approved packaging',
      'Monitor temperature',
    ],
  },
  'Table 2': {
    description: 'May be loaded, transported, or stored together',
    restrictions: [
      'Follow general hazmat regulations',
      'Proper placarding required',
      'Emergency response information available',
    ],
  },
};

export const emergencyResponseCodes = {
  'FIRE': 'Use water spray, foam, dry chemical, or CO2',
  'SPILL': 'Contain spill, prevent entry into waterways',
  'EXPOSURE': 'Remove from exposure, seek medical attention',
  'LEAK': 'Evacuate area, eliminate ignition sources',
};