import { FleetCompany, FleetDriver, FleetVehicle, FleetSettings, ComplianceViolation } from '@/types/fleet';
import { colors } from './colors';

export const mockFleetData = {
  company: {
    id: 'fleet-001',
    name: 'Freedom Logistics LLC',
    logo: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?q=80&w=200',
    primaryColor: colors.primaryLight,
    secondaryColor: colors.secondary,
    contactEmail: 'dispatch@freedomlogistics.com',
    contactPhone: '(555) 123-4567',
    address: '1234 Trucking Way, Atlanta, GA 30309',
    dotNumber: 'DOT-123456',
    mcNumber: 'MC-789012',
    subscription: 'premium' as const,
    createdAt: '2023-01-15',
    isActive: true,
  } as FleetCompany,

  drivers: [
    {
      id: 'driver-001',
      fleetId: 'fleet-001',
      name: 'Michael Johnson',
      email: 'mjohnson@freedomlogistics.com',
      phone: '(555) 234-5678',
      licenseNumber: 'CDL-123456789',
      licenseExpiry: '2025-12-31',
      medicalCertExpiry: '2025-06-15',
      hireDate: '2023-03-01',
      status: 'active' as const,
      vehicleAssigned: 'vehicle-001',
      role: 'driver' as const,
      permissions: ['drive', 'logbook', 'receipts'],
    },
    {
      id: 'driver-002',
      fleetId: 'fleet-001',
      name: 'Sarah Williams',
      email: 'swilliams@freedomlogistics.com',
      phone: '(555) 345-6789',
      licenseNumber: 'CDL-987654321',
      licenseExpiry: '2026-08-15',
      medicalCertExpiry: '2025-12-20',
      hireDate: '2023-01-15',
      status: 'active' as const,
      vehicleAssigned: 'vehicle-002',
      role: 'driver' as const,
      permissions: ['drive', 'logbook', 'receipts', 'maintenance'],
    },
    {
      id: 'driver-003',
      fleetId: 'fleet-001',
      name: 'Robert Davis',
      email: 'rdavis@freedomlogistics.com',
      phone: '(555) 456-7890',
      licenseNumber: 'CDL-456789123',
      licenseExpiry: '2025-10-30',
      medicalCertExpiry: '2025-04-10',
      hireDate: '2023-06-01',
      status: 'inactive' as const,
      role: 'driver' as const,
      permissions: ['drive', 'logbook'],
    },
  ] as FleetDriver[],

  vehicles: [
    {
      id: 'vehicle-001',
      fleetId: 'fleet-001',
      unitNumber: 'FL-4872',
      make: 'Freightliner',
      model: 'Cascadia',
      year: 2022,
      vin: '1FUJGHDV8NLAA1234',
      licensePlate: 'GA-TRK-001',
      assignedDriverId: 'driver-001',
      status: 'active' as const,
      lastInspection: '2025-07-10',
      nextMaintenanceDue: '2025-08-15',
      mileage: 245780,
    },
    {
      id: 'vehicle-002',
      fleetId: 'fleet-001',
      unitNumber: 'FL-4873',
      make: 'Peterbilt',
      model: '579',
      year: 2021,
      vin: '1XP5DB9X8MD567890',
      licensePlate: 'GA-TRK-002',
      assignedDriverId: 'driver-002',
      status: 'active' as const,
      lastInspection: '2025-07-08',
      nextMaintenanceDue: '2025-07-20',
      mileage: 198450,
    },
    {
      id: 'vehicle-003',
      fleetId: 'fleet-001',
      unitNumber: 'FL-4874',
      make: 'Kenworth',
      model: 'T680',
      year: 2020,
      vin: '1XKYDP9X8LJ123456',
      licensePlate: 'GA-TRK-003',
      status: 'maintenance' as const,
      lastInspection: '2025-07-05',
      nextMaintenanceDue: '2025-07-18',
      mileage: 312000,
    },
  ] as FleetVehicle[],

  settings: {
    fleetId: 'fleet-001',
    companyBranding: {
      showLogo: true,
      customColors: true,
      welcomeMessage: 'Welcome to Freedom Logistics - Drive Safe, Drive Smart',
    },
    complianceRules: {
      stricterHosRules: true,
      customBreakRequirements: 8,
      mandatoryPreTrip: true,
      requirePostTrip: true,
      customInspectionItems: ['DEF Level Check', 'Load Securement Inspection'],
    },
    features: {
      voiceCommands: true,
      receiptScanning: true,
      loadNegotiation: false,
      routeOptimization: true,
      maintenanceTracking: true,
    },
    notifications: {
      complianceAlerts: true,
      maintenanceReminders: true,
      loadUpdates: true,
      emergencyContacts: ['dispatch@freedomlogistics.com', '(555) 911-HELP'],
    },
    reporting: {
      dailyReports: true,
      weeklyReports: true,
      complianceReports: true,
      customReports: ['Fuel Efficiency', 'Driver Performance', 'Route Analysis'],
    },
  } as FleetSettings,

  violations: [
    {
      id: 'violation-001',
      driverId: 'driver-001',
      driverName: 'Michael Johnson',
      type: 'hos' as const,
      severity: 'minor' as const,
      description: 'Exceeded 11-hour driving limit by 15 minutes',
      date: '2025-07-12',
      resolved: false,
    },
    {
      id: 'violation-002',
      driverId: 'driver-002',
      driverName: 'Sarah Williams',
      type: 'inspection' as const,
      severity: 'major' as const,
      description: 'Pre-trip inspection not completed before driving',
      date: '2025-07-10',
      resolved: true,
      resolvedBy: 'Fleet Manager',
      resolvedAt: '2025-07-11T10:30:00Z',
      notes: 'Driver completed additional training on inspection procedures',
    },
    {
      id: 'violation-003',
      driverId: 'driver-003',
      driverName: 'Robert Davis',
      type: 'documentation' as const,
      severity: 'critical' as const,
      description: 'Medical certificate expired',
      date: '2025-07-08',
      resolved: false,
    },
  ] as ComplianceViolation[],
};